apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: add-task-ingress
  # annotations:
  #   kubernetes.io/ingress.class: addon-http-application-routing  
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: add-task.rajnish.store
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todo-add-task
            port: 
              number: 80
